/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.orclConnection;
import javax.swing.DefaultComboBoxModel;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QuangDuong
 */
public class ThemDoiVaoGiaiDau extends javax.swing.JFrame {


    /**
     * Creates new form ThemDoiVaoGiaiDau
     */
    public ThemDoiVaoGiaiDau() {
        initComponents();
        this.setTitle("Thêm đội tham gia");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_TenGiai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_DanhSachDoiThamGia = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_DanhSachDoi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên giải đấu");

        cb_TenGiai.setModel(getComboBoxModel());

        jLabel2.setText("Danh sách đội");

        tbl_DanhSachDoiThamGia.setModel(getTableModel_ForDSDoiThamGia());
        jScrollPane2.setViewportView(tbl_DanhSachDoiThamGia);

        jLabel3.setText("Danh sách đội tham gia giải");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        tbl_DanhSachDoi.setModel(getTableModel_ForDSDoi());
        tbl_DanhSachDoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhSachDoiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_DanhSachDoi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_TenGiai, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btn_huy))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_TenGiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_huy))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getMaGiai() {
        String selectedTenGiai = this.cb_TenGiai.getSelectedItem().toString();
        String maGiai = "";

        try {
            Connection conn = new orclConnection().getConnection();
            String SQL = "select mag from GIAIDAU where tengiai = ?";

            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, selectedTenGiai);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                maGiai = rs.getString(1);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        return maGiai;
    }

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed

        try {
            int x = 0;
            Connection conn = new orclConnection().getConnection();
            String SQL = "insert into ct_gd values (?, ?)";

            for (int i = 0; i < tbl_DanhSachDoiThamGia.getRowCount(); i++) {
                String maDoi = tbl_DanhSachDoiThamGia.getValueAt(i, 0).toString();

                PreparedStatement ps = conn.prepareStatement(SQL);
                ps.setString(1, getMaGiai());
                ps.setString(2, maDoi);

                x = ps.executeUpdate();

            }
            if (x == 1) {
                JOptionPane.showMessageDialog(this, "Them du lieu thanh cong");
            } else {
                JOptionPane.showMessageDialog(this, "Them du lieu that bai");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void tbl_DanhSachDoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DanhSachDoiMouseClicked
        String selectedMaDoi = tbl_DanhSachDoi.getValueAt(tbl_DanhSachDoi.getSelectedRow(), 0).toString();
        String selectedTenDoi = tbl_DanhSachDoi.getValueAt(tbl_DanhSachDoi.getSelectedRow(), 1).toString();

        String[] row = {selectedMaDoi, selectedTenDoi};

        DefaultTableModel tm_DoiThamGia = (DefaultTableModel) tbl_DanhSachDoiThamGia.getModel();
        tm_DoiThamGia.addRow(row);

        DefaultTableModel tm_Doi = (DefaultTableModel) tbl_DanhSachDoi.getModel();
        tm_Doi.removeRow(tbl_DanhSachDoi.getSelectedRow());
    }//GEN-LAST:event_tbl_DanhSachDoiMouseClicked

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed

        DefaultTableModel tblModel = (DefaultTableModel) tbl_DanhSachDoiThamGia.getModel();
        tblModel.setRowCount(0);
        tbl_DanhSachDoi.setModel(getTableModel_ForDSDoi());
    }//GEN-LAST:event_btn_huyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDoiVaoGiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDoiVaoGiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDoiVaoGiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDoiVaoGiaiDau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemDoiVaoGiaiDau().setVisible(true);
            }
        });
    }

    private DefaultTableModel getTableModel_ForDSDoiThamGia() {
        DefaultTableModel model = new DefaultTableModel();

        String[] title = {"Mã đội", "Tên đội"};
        model.setColumnIdentifiers(title);

        return model;
    }

    private DefaultTableModel getTableModel_ForDSDoi() {
        DefaultTableModel model = new DefaultTableModel();

        String[] title = {"Mã đội", "Tên đội"};
        model.setColumnIdentifiers(title);

        try {
            Connection conn = new orclConnection().getConnection();
            String SQL = "select mad, tendoi from DOIBONG";
            String[] row = new String[2];

            PreparedStatement ps = conn.prepareStatement(SQL);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                model.addRow(row);
            }
        } catch (Exception e) {
            System.out.println(e);
        }

        return model;
    }

    private DefaultComboBoxModel getComboBoxModel() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        try {
            Connection conn = new orclConnection().getConnection();
            String SQL = "select tengiai from giaidau";
            ArrayList<String> tengiaiList = new ArrayList<>();

            PreparedStatement ps = conn.prepareStatement(SQL);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                tengiaiList.add(rs.getString(1));
            }

            model = new DefaultComboBoxModel(tengiaiList.toArray());
        } catch (Exception e) {
            System.out.println(e);
        }

        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_them;
    private javax.swing.JComboBox<String> cb_TenGiai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbl_DanhSachDoi;
    private javax.swing.JTable tbl_DanhSachDoiThamGia;
    // End of variables declaration//GEN-END:variables
}
