/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import database.orclConnection;
import javax.swing.DefaultComboBoxModel;
import java.sql.*;
import java.util.ArrayList;

/**
 *
 * @author QuangDuong
 */
public class ThemThongTin extends javax.swing.JFrame {

    /**
     * Creates new form ThemThongTin
     */
    public ThemThongTin() {
        initComponents();
        this.setTitle("Thêm thông tin trận đấu");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_DoiNha = new javax.swing.JComboBox<>();
        tf_DiaDiem = new javax.swing.JTextField();
        tf_NgayDau = new javax.swing.JTextField();
        cb_TenGD = new javax.swing.JComboBox<>();
        cb_DoiKhach = new javax.swing.JComboBox<>();
        tf_TiSo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Them = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên giải đấu");

        cb_DoiNha.setModel(getComboBoxModel_ForDoiNha());
        cb_DoiNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_DoiNhaActionPerformed(evt);
            }
        });

        cb_TenGD.setModel(getComboBoxModel_ForTenGD());

        cb_DoiKhach.setModel(getComboBoxModel_ForDoiKhach());

        jLabel2.setText("Đội khách");

        jLabel3.setText("Ngày đấu");

        jLabel4.setText("Địa điểm");

        jLabel5.setText("Tỉ số");

        jLabel6.setText("Đội nhà");

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_TiSo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tf_NgayDau)
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_Them)
                                            .addComponent(cb_DoiNha, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tf_DiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_DoiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btn_Huy))))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_TenGD, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_TenGD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_DiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_NgayDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_DoiNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_DoiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_TiSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Huy))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        cb_TenGD.setSelectedIndex(0);
        cb_DoiNha.setSelectedIndex(0);
        cb_DoiKhach.setSelectedIndex(0);
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void cb_DoiNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_DoiNhaActionPerformed
        cb_DoiKhach.setModel(getComboBoxModel_ForDoiKhach());
    }//GEN-LAST:event_cb_DoiNhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemThongTin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemThongTin().setVisible(true);
            }
        });
    }

    private DefaultComboBoxModel getComboBoxModel_ForDoiKhach() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        try {
            Connection conn = new orclConnection().getConnection();
            String SQL = "select TENDOI "
                    + "from DOIBONG where TENDOI != ?";
            ArrayList<String> arrayList = new ArrayList<>();
            arrayList.add("Chọn tên đội khách");

            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, getTenDoiNha());

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                arrayList.add(rs.getString(1));
            }

            model = new DefaultComboBoxModel(arrayList.toArray());
        } catch (Exception e) {
            System.out.println(e + " at getComboBoxModel_ForDoiKhach()");
        }

        return model;
    }

    private DefaultComboBoxModel getComboBoxModel_ForDoiNha() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        try {
            Connection conn = new orclConnection().getConnection();
            String SQL = "select D.TENDOI "
                    + "from DOIBONG D ";
            ArrayList<String> arrayList = new ArrayList<>();
            arrayList.add("Chọn tên đội nhà");
            PreparedStatement ps = conn.prepareStatement(SQL);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                arrayList.add(rs.getString(1));
            }

            model = new DefaultComboBoxModel(arrayList.toArray());
        } catch (Exception e) {
            System.out.println(e + " at getComboBoxModel_ForDoiNha()");
        }

        return model;
    }

    private DefaultComboBoxModel getComboBoxModel_ForTenGD() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        try {
            Connection conn = new orclConnection().getConnection();
            String SQL = "select tengiai from giaidau";
            ArrayList<String> tengiaiList = new ArrayList<>();
            tengiaiList.add("Chọn tên giải");

            PreparedStatement ps = conn.prepareStatement(SQL);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                tengiaiList.add(rs.getString(1));
            }

            model = new DefaultComboBoxModel(tengiaiList.toArray());

        } catch (Exception e) {
            System.out.println(e);
        }

        return model;
    }

    private String getTenDoiNha() {
        return cb_DoiNha.getSelectedItem().toString();
    }

//    private String getMaGD() {
//        String maGiai = null;
//
//        try {
//            Connection conn = new orclConnection().getConnection();
//            String SQL = "select C.MAG "
//                    + "from GIAIDAU G join CT_GD C on C.MAG =  G.MAG "
//                    + "where TENGIAI = ?";
//
//            PreparedStatement ps = conn.prepareStatement(SQL);
//            ps.setString(1, cb_TenGD.getSelectedItem().toString());
//
//            ResultSet rs = ps.executeQuery();
//
//            while (rs.next()) {
//                maGiai = rs.getString(1);
//            }
//        } catch (Exception e) {
//            System.out.println(e + " at getMaGD()");
//        }
//
//        return maGiai;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_Them;
    private javax.swing.JComboBox<String> cb_DoiKhach;
    private javax.swing.JComboBox<String> cb_DoiNha;
    private javax.swing.JComboBox<String> cb_TenGD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_DiaDiem;
    private javax.swing.JTextField tf_NgayDau;
    private javax.swing.JTextField tf_TiSo;
    // End of variables declaration//GEN-END:variables
}
